---

dns_domain_name: cncbi.local

mssql_username: sqladmin
mssql_password: 'Redacted$12#'

sql_server_instance_name: 'MSSQLSERVER'
sql_server_sys_admin_accounts:
  - '{{ mssql_username }}'
sql_server_features:
  - SQLENGINE
  - FullText
  - Replication
sql_server_svc_account_name: SASQLSvcAccount
sql_server_agt_svc_account_name: SAAgtSvcAccount
sql_server_svc_accounts_password: 'Redacted$12#'
sql_server_local_users: false

sql_server_svc_account: '{{ domain_prefix | upper }}\{{ sql_server_svc_account_name }}'
sql_server_agt_svc_account: '{{ domain_prefix | upper }}\{{ sql_server_agt_svc_account_name }}'

iso_path: '{{ ansible_env.TEMP }}\sql2019.iso'
iso_url: 'z:\SQLServer2019-x64-ENU.iso'
